# fly.toml app configuration file generated for heimdallr-test on 2026-02-26T21:37:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heimdallr-test'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'heimdallr'
  destination = '/var/lib/heimdallr'

[http_service]
  internal_port = 8484
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
